import {
  AcademicCapIcon,
  RocketLaunchIcon,
  MusicalNoteIcon,
  PhotoIcon,
  DocumentTextIcon,
  ShoppingBagIcon,
  FireIcon,
  FolderIcon,
  CogIcon,
} from "@heroicons/react/24/outline";

export const actions = [
  {
    icon: PhotoIcon,
    name: "Image Generation",
    description:
      "Generate images from text and images. Features include inpainting, multiple models and more.",
    href: "app/image-generation",
    status: true,
    iconColor: "z-icon z-indigo",
    border: "z-border-purple",
  },
  {
    icon: MusicalNoteIcon,
    name: "Audio Generation",
    description:
      "Generate audio samples for your projects. We fintuned multiple models on different types of drums for you to use.",
    href: "app/audio-generation",
    status: false,
    iconColor: "z-icon z-orange",
    border: "z-border-orange",
  },
  {
    icon: FireIcon,
    name: "Explore",
    description:
      "Share and explore the latest images generated by the community. You can also upvote and comment on images.",
    href: "app/explore",
    status: true,
    iconColor: "z-icon z-red",
    border: "z-border-red",
  },

  {
    icon: ShoppingBagIcon,
    name: "Synthx Shop",
    description: "Design one of a kind products using AI.",
    href: "app/shop",
    status: false,
    iconColor: "z-icon z-emerald",
    border: "z-border-emerald",
  },
  {
    icon: DocumentTextIcon,
    name: "APSEO",
    description:
      "Artifical Programatic SEO. Generate SEO optimized content using a dataset and Large Language Models.",
    href: "app/apseo",
    status: false,
    iconColor: "z-icon z-yellow",
    border: "z-border-yellow",
  },
  {
    icon: FolderIcon,
    name: "Storage",
    description:
      "View your generated images and audio samples. You can also download and share them.",
    href: "app/storage",
    status: true,
    iconColor: "z-icon z-rose",
    border: "z-border-rose",
  },
  {
    icon: CogIcon,
    name: "Settings",
    description:
      "Manage your account and change your settings. You can also view your billing information.",
    href: "app/settings",
    status: true,
    iconColor: "z-icon z-teal",
    border: "z-border-teal",
  },
  {
    icon: AcademicCapIcon,
    name: "Documentation",
    description:
      "Learn how to use our platform and how to integrate it into your projects.",
    href: "/docs",
    status: true,
    iconColor: "z-icon z-violet",
    border: "z-border-violet",
  },
];
export type Action = typeof actions[number];
