import {
  FireIcon,
  FolderIcon,
  MusicalNoteIcon,
  PhotoIcon,
  RocketLaunchIcon,
  StarIcon,
} from "@heroicons/react/24/outline";

export const updates = [
  {
    id: 1,
    content: "Basic audio generation added for early access accounts.",
    target: "Learn more",
    href: "#",
    date: "Jan 14",
    datetime: "2023-01-14",
    icon: MusicalNoteIcon,
    iconBackground: "bg-gray-400",
  },
  {
    id: 2,
    content: "Upscaling page added and built into image generation page.",
    target: "Learn more",
    href: "#",
    date: "Jan 7",
    datetime: "2023-01-07",
    icon: PhotoIcon,
    iconBackground: "bg-blue-500",
  },
  {
    id: 3,
    content: "Basic image editing features added.",
    target: "Learn more",
    href: "#",
    date: "Jan 5",
    datetime: "2023-01-05",
    icon: PhotoIcon,
    iconBackground: "bg-green-500",
  },
  {
    id: 4,
    content: "Explore page and profiles pages added.",
    target: "Learn more",
    href: "#",
    date: "Jan 4",
    datetime: "2023-01-04",
    icon: FireIcon,
    iconBackground: "bg-green-500",
  },
  {
    id: 5,
    content: "Storage and Settings pages added.",
    target: "Learn more",
    href: "#",
    date: "Jan 3",
    datetime: "2023-01-03",
    icon: FolderIcon,
    iconBackground: "bg-green-500",
  },
  {
    id: 6,
    content: "10 new image models added.",
    target: "Learn more",
    href: "#",
    date: "Jan 2",
    datetime: "2023-01-01",
    icon: StarIcon,
    iconBackground: "bg-blue-500",
  },
  {
    id: 7,
    content: "Alpha Release!",
    target: "Read whats new.",
    href: "#",
    date: "Jan 1",
    datetime: "2022-12-31",
    icon: RocketLaunchIcon,
    iconBackground: "bg-green-500",
  },
];

export type Update = typeof updates[number];
